/* eslint-disable react/jsx-key */
import type { NextPage } from "next";
import { useEffect, useState } from "react";
import Head from "next/head";
import styles from "../styles/Home.module.css";
import Phone from "../components/Phone/Phone.js";
import QRCode from "../components/QRCode/QRCode.js";
import InfoCard from "../components/InfoCard/InfoCard.js";
import BoostcampStar from "../pages/images/logo.svg";
import InstructionsImage from "../pages/images/instructions.svg";
import InstructionCard from "../components/InstructionCard/InstructionCard.js";

const Home: NextPage = () => {
  return (
    <main id="main_container" className={styles.main_container}>
      <Head>
        <title>Boostcamp</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className={styles.content}>
        <div className={styles.landing_container}>
          <div className={styles.multicolour_background}></div>
          <div className={styles.page_heading}>
            <QRCode />
          </div>
          <div className={styles.phone_container}>
            <Phone phoneDisplay={false}></Phone>
          </div>
        </div>
        <div className={styles.teampage_container}>
          <InfoCard
            isYoga={false}
            heading={`As six School of Code bootcampers, `}
            subHeading={`we came together to complete a final project.`}
            paragraph={`With six unique backgrounds and perspectives, we set out to build an application that would benefit future bootcampers (or anyone else in need of a boost!)`}
          ></InfoCard>
        </div>
        <div className={styles.mission_container}>
          <InfoCard
            isYoga={true}
            heading={`Complete random tasks`}
            subHeading={`that are different every day.`}
            paragraph={`Sometimes people get caught up in the intensity of modern life. We aim to harness the power of randomness to brighten people’s day. `}
          ></InfoCard>
        </div>
        <div className={styles.instructions_container}>
          <div className={styles.instructions_content}>
            <div className={styles.gif_container}>
              <img
                className={styles.phone}
                src={InstructionsImage.src}
                alt="image of app in use"
              />
            </div>
            <div className={styles.instructions}>
              <div className={styles.title_container}>
                <img
                  className={styles.instructions_star}
                  src={BoostcampStar.src}
                  alt="boostcamp star"
                />
                <h1 className={styles.instructions_heading}>
                  BOOST your mood!
                </h1>
              </div>
              <h2 className={styles.instructions_subheading}>
                How to unlock the power of BoostCamp
              </h2>
              <div className={styles.instruction_cards}>
                <InstructionCard isActive={true} text={"1. Choose a Type"} />
                <InstructionCard isActive={true} text={"2. Choose a Task"} />
                <InstructionCard
                  isActive={true}
                  text={"3. Complete your Task!"}
                />
              </div>
              <div className={styles.downloadContainer}>
                <a
                  id="downloadButton"
                  className={styles.downloadButton}
                  target={"_blank"}
                  rel="noreferrer"
                  href={`https://expo.dev/@teamcaarve/Boostcamp?serviceType=classic&distribution=expo-go`}
                >
                  <div className={styles.shine}>Download on Expo</div>
                </a>
              </div>
            </div>
          </div>
          <div className={styles.downloadContainerPhone}>
            <a
              id="downloadButtonPhone"
              className={styles.downloadButton}
              target={"_blank"}
              rel="noreferrer"
              href={`https://expo.dev/@teamcaarve/Boostcamp?serviceType=classic&distribution=expo-go`}
            >
              <div className={styles.shine}>
                Download <br></br>on Expo
              </div>
            </a>
          </div>
          <div className={styles.multicolour_footer}></div>
        </div>
      </div>
    </main>
  );
};

export default Home;
