import type { NextPage } from 'next';
import Head from 'next/head';
import styles from '../styles/Home.module.css';

const Home: NextPage = () => {
  return (
    <div className={styles.container}>
      <Head>
        <title>Boostcamp</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <div className={styles.logoContainer}>
          <img
            src="https://classic-assets.eascdn.net/~assets/2a8eafca97f5e02149e1f4b805120a5e"
            className={styles.image}
          />
          <h1 className={styles.title}>BOOSTCAMP</h1>
        </div>

        <p className={styles.description}>By Team Caarve</p>

        <div className={styles.grid}>
          <a
            href="https://expo.dev/@teamcaarve/Boostcamp?serviceType=classic&distribution=expo-go"
            className={styles.card}
          >
            <h2>Try Now on Expo &rarr;</h2>
          </a>
        </div>
      </main>

      <footer className={styles.footer}>
        <a href="#" target="_blank" rel="noopener noreferrer">
          Conor McGuigan, Adam Story, Austyn Tempesta, Richard McKenzie, Vic
          Khatian, Elena Souto.
        </a>
      </footer>
    </div>
  );
};

export default Home;
